# Coin Flips and their Statistics

This script simulates a series of coin flips and calculates it's associated statistics.

Flipping a coin is a binomiam process. i.e. The outcome can either be a HEAD or a TAIL.

A fair coin is statistically expected to yield the same number of HEADs and TAILs. Hence, the probability of getting a HEAD is 0.5.

The outcomes are encoded as.
- 1 -> HEAD
- 0 -> TAIL

In [21]:
%reload_ext autoreload
%autoreload 2

In [23]:
import numpy as np
import scipy as sp
import plotly.graph_objects as go
import plotly.express as px
import utils

### Simulating coin flips

In [26]:
# Check default parameter values.

# Test the function with 10 flips, and 3 ensembles
head_outcomes = utils.flip_coin(n_flips=10, n_ensembles=3)
print(head_outcomes)

# Test the function with 10 flips, and 1 ensemble
head_outcomes_single = utils.flip_coin(n_flips=10)
print(head_outcomes_single)

[[1 0 1 0 0 1 1 1 1 1]
 [0 1 1 0 0 0 0 1 0 0]
 [0 1 0 0 0 1 0 0 0 1]]
[1 1 1 1 1 0 1 0 1 1]


### Checking if a coin is FAIR or not

In [ ]:
# Simulation parameters
n_flips_sim = 100
p_head_sim = 0.5
# sigma_threshold = 2

# Simulate coin flips
head_outcomes = utils.flip_coin(n_flips=n_flips_sim, p_head=p_head_sim)

# Analyze the outcomes
n_heads = np.sum(head_outcomes)
is_fair, p_head_ML, sigma_p_head_ML, num_sigma_from_fair = utils.is_coin_fair(head_outcomes)

print(f"In {n_flips_sim} flips, there were {n_heads} heads and {n_flips_sim - n_heads} tails.")
print(f"The fraction of heads is {p_head_ML:.3f}.")
print(f"The estimated standard deviation of the fraction of heads is {sigma_p_head_ML:.3f}.")
print(f"The number of standard deviations from a fair coin (p_head = 0.5) is {num_sigma_from_fair:.2f}.")
if is_fair:
    print("The coin is estimated to be FAIR.")
else:
    print("The coin is estimated to be UNFAIR.")

In 100 flips, there were 45 heads and 55 tails.
The fraction of heads is 0.450.
The estimated standard deviation of the fraction of heads is 0.050.
The number of standard deviations from a fair coin (p_head = 0.5) is 1.01.
The coin is estimated to be FAIR.


In [ ]:
# Parameters of analysis
p_head_ML = 0.51
n_flips = 1000
sigma_threshold = 2

num_std = utils.num_std_away_from_fair(p_head_ML, n_flips)
is_fair = num_std < sigma_threshold
print(f"An average of {p_head_ML:.2f} heads per {n_flips} flips is {num_std:.2f} sigmas away from a fair coin.\nAnd is therefore {'FAIR' if is_fair else 'UNFAIR'}")  # Example usage of num_std_away_from_fair


An average of 0.51 heads per 1000 flips is 0.63 sigmas away from a fair coin.
And is therefore FAIR


### Power of a test

How many trials are needed to determine if a certain outcome disproves FAIRness.

NOTE: We are only able to disprove FAIRness given a threshold or confidence.

Sensitivity is the gap between the condition to be FAIR and the observation.

Ex. If the ML outcome is 63% HEADs, then the gap is 0.13.

In [33]:
# Analysis parameters
sensitivity = 0.05  # The gap from 0.5 to the observed p_head_ML
sigma_threshold = 2  # The number of standard deviations to use as a threshold for FAIRness

num_flips_thres = utils.num_flips_to_achieve_sigma(sensitivity = sensitivity,
                                                   sigma_threshold = sigma_threshold)

print(f"To detect a gap of {sensitivity:.2f} from FAIRness with a threshold of {sigma_threshold} sigmas, \nwe need at least {num_flips_thres} flips.")

To detect a gap of 0.05 from FAIRness with a threshold of 2 sigmas, 
we need at least 396 flips.
